# P15–P16 — Reproducibilidad, congelamiento e incidencias
## (a) Paso del protocolo y objetivo
**P15:** dejar **evidencia reproducible**: entorno fijado (versiones exactas), semillas, huellas sha256 y el **modelo congelado** (compuerta **G5**: el modelo de las sesiones es *exactamente* el medido en G3, con las respuestas verificadas de G4). **P16:** registrar **toda** desviación o error en `incident_log.csv`; ninguna se resuelve en silencio. Sustentan el **OE2** (la arquitectura es reproducible) y la validez de todos los demás resultados.
**Origen:** huellas y versiones **Reales** (hashes, sin datos); la bitácora y la matriz de trazabilidad son registros del proyecto.

## (b) Código del repositorio que lo implementa
`congelar_modelo.py` (congela y verifica con `--verificar`), `verificar_referencias.py` (contrasta rutas y cifras del protocolo con el repositorio), `auditar_diseno_piloto.py` y `auditar_fecha_corte.py` (auditorías de consistencia documental), `estado_compuertas.py` (tablero) y los scripts de este material (`construir_colab*.py`, `colab_util.py`, `colab_metadatos.py`). Entradas: modelo, dominio, configuración, entrenamiento, umbral; Salidas: `logs/v3_real/modelo_congelado.json`, `incident_log.csv`.

In [1]:
# ----- Preparación mínima (igual en todos los cuadernos) -----
import os, sys, zipfile
from pathlib import Path

EN_COLAB = "google.colab" in sys.modules
if EN_COLAB:
    from google.colab import drive
    drive.mount("/content/drive")
    CARPETA_DRIVE = Path("/content/drive/MyDrive/MPSR_colab")
    BASE = Path("/content/mpsr")
else:
    CARPETA_DRIVE = Path(os.environ.get("MPSR_DRIVE", ".")).resolve()
    BASE = Path(os.environ.get("MPSR_BASE", "mpsr_trabajo")).resolve()
BASE.mkdir(parents=True, exist_ok=True)
ZIP_PUBLICO = CARPETA_DRIVE / "MPSR_colab_publico.zip"
if not ZIP_PUBLICO.exists():
    raise SystemExit(f"Falta {ZIP_PUBLICO}. Sube MPSR_colab_publico.zip a la carpeta MPSR_colab de tu Drive (ver LEEME_colab_por_paso.md).")
if not (BASE / "scripts" / "colab_util.py").exists():          # solo descomprime la primera vez
    with zipfile.ZipFile(ZIP_PUBLICO) as z:
        z.extractall(BASE)
sys.path.insert(0, str(BASE / "scripts"))
import colab_util as U
U.iniciar(BASE, CARPETA_DRIVE)                                  # rutas, paquete privado (si existe) y detección de Rasa
from colab_util import *                                        # rotulo, comparar, sha256, leer_json, tabla_scripts, ic_bootstrap, ...

Listo · BASE = base · paquete privado: SÍ · Rasa: no instalado (no hace falta)

In [2]:
tabla_scripts(scripts_de("12"))

▌ORIGEN: Código del proyecto (no es dato del estudio)

                         script          paso del protocolo                                                  propósito (docstring)                                               entradas                                                                salidas                                                        cómo ejecutarlo     usa Rasa                               rol en este cuaderno
0      auditar_diseno_piloto.py             P12 (auditoría)  Auditoría de las menciones al diseño anterior del piloto (V1.2: 12...                             Documentos del repositorio  Menciones al diseño anterior (120 personas) frente al vigente (n =...                                python scripts/auditar_diseno_piloto.py           No                                        Documentado
1        auditar_fecha_corte.py            2.14 (auditoría)  Auditoría de «fecha de corte» / «fecha límite» / «plazo» frente a ...                             Documentos del repositorio                   Menciones a «fecha de corte» frente a las compuertas                                  python scripts/auditar_fecha_corte.py           No                                        Documentado
2            capturas_avance.py  Evidencias de avance (P15)  Capturas (PNG) de las salidas REALES guardadas en los cuadernos y ...                 Cuadernos ejecutados y logs existentes                      evidencias/capturas_avance/ (PNG, INDICE.md, PDF)  python scripts/capturas_avance.py ejecutar-local     corre en vivo...           No                                        Documentado
3            colab_metadatos.py       Documentación (Colab)  Metadatos CURADOS a mano para el cuaderno de Colab (Colab_Avance_M...                                                      —  Tablas curadas (paso del protocolo, glosario, trazabilidad) que le...                               python scripts/colab_metadatos.py --help           No                                        Documentado
4                 colab_util.py       Documentación (Colab)  Utilidades comunes de los cuadernos de Colab por paso (notebooks/c...                                                      —  Funciones comunes de los cuadernos por paso: rutas, rótulos, compa...                                    python scripts/colab_util.py --help  Sí (import)          Documentado (se importa en cada cuaderno)
5            congelar_modelo.py                          G5          Congela el modelo que se usará en el piloto (protocolo V1.3).  Modelo, dominio, entrenamiento, configuración, umbral                 logs/v3_real/modelo_congelado.json; opción --verificar  python scripts/congelar_modelo.py --modelo models/v3_real/<modelo>...           No                       Lógica recalculada (etapa 6)
6            construir_colab.py       Documentación (Colab)  Construye el material de Colab del proyecto (Colab_Avance_MPSR_v1)...                    Repositorio (solo lectura) + tests/  colab_paquetes/*.zip, notebooks/Colab_Avance_MPSR_v1.ipynb, docs/D...  python scripts/construir_colab.py --todo --incluir-privado        ...           No  Documentado (genera este cuaderno y los paquetes)
7   construir_colab_por_paso.py       Documentación (Colab)  Divide el cuaderno único (Colab_Avance_MPSR_v1) en cuadernos por p...                              Cuaderno único + paquetes       notebooks/colab_por_paso/*.ipynb, colab_paquetes/colab_por_paso/  python scripts/construir_colab_por_paso.py --etiquetas       (list...           No        Documentado (genera los cuadernos por paso)
8          estado_compuertas.py                2.14 (G1–G7)  Tablero de las compuertas de avance (protocolo V1.4, sección 2.14,...                 Archivos de evidencia de logs/ y docs/                                logs/avance/estado_compuertas.{json,md}                                    python scripts/estado_compuertas.py           No                      Resultado guardado (etapa 12)
9        evidencia_ejecucion.py  Evidencias de avance (P15)  PDF «Evidencia de ejecución» (pruebas): entrenamiento, métodos com...          Cuadernos ejecutados y registros de ejecución        evidencias/capturas_avance/Evidencia_Ejecucion.pdf (sin fechas)  python scripts/evidencia_ejecucion.py        (requiere los .zip ya...           No                                        Documentado
10     verificar_referencias.py                     P15/P16  Verifica que las rutas y las cifras citadas en el protocolo V1.8 y...                Protocolo V1.8 y Nota v11 + repositorio  Informe con 61 afirmaciones del protocolo/Nota: 59 OK y 0 discrepa...                                python scripts/verificar_referencias.py           No                                        Documentado

## (c) Celdas de código
### 1. Entorno y semillas

### Entorno y reproducibilidad
**Qué se hace:** se registran las versiones de Python y de las librerías, las semillas, la carpeta de trabajo, y (en Colab) se monta Drive y se descomprimen los paquetes.
**Por qué:** la reproducibilidad (paso P15 del protocolo) exige poder decir con qué versiones se obtuvo cada cifra. El modelo congelado se entrenó con **Python 3.10.11, Rasa 3.6.21, TensorFlow 2.12.0, scikit-learn 1.1.3, numpy 1.23.5** (`requirements.txt`).
**Qué necesita Rasa y qué no:** Rasa 3.6 exige Python 3.8–3.10 y numpy < 1.24; **el Colab actual trae Python más nuevo**, así que *no se instala Rasa*. Todo lo demás (pandas, scikit-learn, scipy, hashes, tablero, alfa de Cronbach, métricas, bootstrap, McNemar) corre siempre. Lo único que depende de Rasa es **entrenar/cargar el modelo DIET**; para eso el cuaderno usa las **predicciones y resultados guardados** y lo declara en cada celda.

In [3]:
# ----- Versiones, semillas y capacidades -----
versiones = {"Python": platform.python_version(), "Sistema": platform.system() + " " + platform.release(), "numpy": np.__version__, "pandas": pd.__version__}
for mod in ("scipy", "sklearn", "matplotlib", "openpyxl", "yaml"):
    try:
        m = __import__(mod)
        versiones[mod] = getattr(m, "__version__", "?")
    except ImportError:
        versiones[mod] = "NO instalado"
versiones["Rasa"] = VERSION_RASA or "no instalado (no es necesario para este cuaderno)"
rotulo("Entorno de ejecución de este cuaderno (no es dato del estudio)")
display(pd.DataFrame({"componente": list(versiones), "versión aquí": list(versiones.values())}))

ref = leer_json("logs/v3_real/modelo_congelado.json")
rotulo("Entorno con el que se entrenó el modelo congelado (leído de modelo_congelado.json)")
display(pd.DataFrame({"componente": list(ref["versiones"]), "versión del congelamiento": list(ref["versiones"].values())}))
print("Semilla global del proyecto: 42 (DIET, SVM, particiones y bootstrap). Remuestreos del bootstrap: 1000.")
print("Rasa disponible aquí:", HAY_RASA, "| Colab:", EN_COLAB)

▌ORIGEN: Entorno de ejecución de este cuaderno (no es dato del estudio)

   componente                                       versión aquí
0      Python                                            3.10.11
1     Sistema                                         Windows 10
2       numpy                                             1.23.5
3      pandas                                              2.0.3
4       scipy                                             1.10.1
5     sklearn                                              1.1.3
6  matplotlib                                              3.5.3
7    openpyxl                                              3.1.5
8        yaml                                              6.0.3
9        Rasa  no instalado (no es necesario para este cuaderno)

▌ORIGEN: Entorno con el que se entrenó el modelo congelado (leído de modelo_congelado.json)

     componente versión del congelamiento
0          rasa                    3.6.21
1  scikit-learn                     1.1.3
2        pandas                     2.0.3
3         numpy                    1.23.5
4         scipy                    1.10.1
5    tensorflow                    2.12.0

Semilla global del proyecto: 42 (DIET, SVM, particiones y bootstrap). Remuestreos del bootstrap: 1000.
Rasa disponible aquí: False | Colab: False

### Cómo leer el resultado de esta sección
- La primera tabla dice **dónde corre este cuaderno**; la segunda, **con qué se entrenó el modelo congelado**. Si `scikit-learn`/`numpy` difieren, los números de métricas recalculadas (que dependen solo de fórmulas) no cambian, pero **no se puede cargar un modelo `.joblib`/`.tar.gz` entrenado con otra versión**: por eso no se carga ningún modelo en el cuaderno.
- «Rasa disponible: False» es lo esperado en Colab. Las etapas que normalmente usarían Rasa muestran en su lugar los resultados guardados (etapas 6 y 7).

### 2. Las versiones de `requirements.txt` coinciden con las del congelamiento (Real)

In [4]:
fz = leer_json("logs/v3_real/modelo_congelado.json")
req = {}
for l in (BASE / "requirements.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"^([A-Za-z0-9_.-]+)==([\w.]+)", l.strip())
    if m:
        req[m.group(1).lower()] = m.group(2)
rotulo(ORIGEN_REAL, "versiones del modelo congelado frente a requirements.txt")
filas = []
for pkg, v in fz["versiones"].items():
    filas.append({"paquete": pkg, "congelamiento": v, "requirements.txt": req.get(pkg.lower()), "coincide": req.get(pkg.lower()) == v})
    comparar("P15", f"versión de {pkg}", req.get(pkg.lower()), v, "requirements.txt frente a modelo_congelado.json", tipo="txt")
display(pd.DataFrame(filas))
print("Python del congelamiento:", fz["python"], "| commit declarado:", fz["commit"])

▌ORIGEN: Real — versiones del modelo congelado frente a requirements.txt

        paquete congelamiento requirements.txt  coincide
0          rasa        3.6.21           3.6.21      True
1  scikit-learn         1.1.3            1.1.3      True
2        pandas         2.0.3            2.0.3      True
3         numpy        1.23.5           1.23.5      True
4         scipy        1.10.1           1.10.1      True
5    tensorflow        2.12.0           2.12.0      True

Python del congelamiento: 3.10.11 | commit declarado: 98d549a-modificado

### 3. Congelamiento e integridad del modelo (G5)

### Congelamiento y verificación de integridad (G5)
**Qué se hace:** se **recalcula el sha256** de cada componente del modelo congelado (modelo, configuración, dominio, conjunto de entrenamiento y umbral) y se compara con `modelo_congelado.json`. Se muestra «intacto» o la discrepancia.
**Por qué:** G5 exige que el modelo con el que se hacen las sesiones sea **exactamente** el medido en G3 (y que las respuestas verificadas en G4 ya formen parte de él). Si un solo byte cambia, el congelamiento se invalida.
**Paso del protocolo:** G5 (antes de la primera sesión del pre-piloto).

In [5]:
fz = leer_json("logs/v3_real/modelo_congelado.json")
previo = leer_json("logs/v3_real/lote2_congelado_previo.json")
rutas = {"modelo": PRIV / "artefactos_congelados/LOTE2-FINAL.tar.gz", "config": BASE / "configs/rasa_config_lote2.yml", "dominio": BASE / "domain_v3.yml",
         "corpus": PRIV / "artefactos_congelados/entrenamiento_lote2.csv", "umbral": BASE / "logs/v3_real/lote2_umbral_congelado.json"}
filas, hay_dif, no_verificables = [], False, 0
for k, esperado in fz["sha256"].items():
    p = rutas[k]
    if p.exists():
        calc = sha256(p)
        estado = "intacto" if calc == esperado else "DISCREPANCIA"
        hay_dif |= calc != esperado
        comparar("G5", f"sha256 {k}", calc, esperado, "logs/v3_real/modelo_congelado.json", tipo="txt")
    else:
        calc, estado = "—", "no verificable aquí (requiere paquete privado)"
        no_verificables += 1
    filas.append({"componente": k, "sha256 congelado (12)": esperado[:12], "sha256 recalculado (12)": calc[:12], "estado": estado, "igual al congelamiento previo al lote 2": previo["sha256"].get(k) == esperado})
rotulo(ORIGEN_REAL, "huellas del modelo congelado LOTE2-FINAL v1 (hashes, sin datos)")
display(pd.DataFrame(filas))
if hay_dif:
    print("¡¡DISCREPANCIA!! Al menos un componente cambió: el congelamiento NO está intacto.")
elif no_verificables:
    print(f"Sin discrepancias en los componentes verificados; {no_verificables} componente(s) requieren el paquete privado.")
else:
    print("Congelamiento: INTACTO (los 5 componentes coinciden).")
um = leer_json("logs/v3_real/lote2_umbral_congelado.json")
print("Umbral congelado: t =", um["t"], "| ambigüedad =", um.get("ambiguity_threshold"), "| versión:", fz["version"])
print("Frases de entrenamiento declaradas:", fz["frases_entrenamiento"], "| Python/Rasa del congelamiento:", fz["python"], "/", fz["versiones"]["rasa"])
comparar("G5", "umbral t", um["t"], 0.5, "Protocolo V1.8", tol=0)
comparar("G5", "frases de entrenamiento", fz["frases_entrenamiento"], 943, "Protocolo V1.8 (707 + 185 + 51)", tol=0)

▌ORIGEN: Real — huellas del modelo congelado LOTE2-FINAL v1 (hashes, sin datos)

  componente sha256 congelado (12) sha256 recalculado (12)   estado  igual al congelamiento previo al lote 2
0     modelo          be1a5ad06357            be1a5ad06357  intacto                                     True
1     config          e975783f2bcd            e975783f2bcd  intacto                                     True
2    dominio          7a69ac91c32c            7a69ac91c32c  intacto                                     True
3     corpus          c035252d63aa            c035252d63aa  intacto                                     True
4     umbral          410d9898240a            410d9898240a  intacto                                     True

Congelamiento: INTACTO (los 5 componentes coinciden).
Umbral congelado: t = 0.5 | ambigüedad = 0.1 | versión: LOTE2-FINAL v1 (DIET 100/64/20, seed 42, 943 frases de entrenamiento, umbral t=0,50)
Frases de entrenamiento declaradas: 943 | Python/Rasa del congelamiento: 3.10.11 / 3.6.21

### Cómo leer el resultado de esta sección
- **«intacto»** en los cinco componentes = el modelo, el dominio (las 54 respuestas), la configuración, el entrenamiento (943 frases) y el umbral son exactamente los congelados. Los 12 primeros caracteres del hash bastan para una lectura visual; la comparación usa los 64.
- La columna «igual al congelamiento previo al lote 2» confirma que se congeló **antes de abrir el lote 2** (`lote2_congelado_previo.json`) y no se reentrenó después de ver los resultados.
- Con solo el paquete público se verifican dominio, configuración y umbral; el **modelo** (33 MB) y el **entrenamiento** viajan en el paquete privado. Esto replica la opción `--verificar` de `scripts/congelar_modelo.py`, sin cargar el modelo (no hace falta Rasa).

### 4. P16 — Bitácora de incidencias

### Bitácora de incidencias (P16)
**Qué se hace:** se lee `incident_log.csv` y se muestra como tabla: fecha, incidencia, decisión y justificación, más dos columnas **orientativas** (`tipo` técnica/metodológica y `afecta validez`).
**Por qué:** el protocolo manda registrar **toda** desviación; ninguna se resuelve en silencio. La bitácora es la evidencia de que los cambios y errores quedaron declarados.
**Aviso:** el archivo original **no** tiene las columnas «tipo» ni «afecta validez»; aquí se *infieren por palabras clave* solo para orientar la lectura. Son una heurística, no una clasificación del tesista.

In [6]:
inc = pd.read_csv(BASE / "incident_log.csv", dtype=str, keep_default_na=False, encoding="utf-8")
inc.columns = ["fecha", "incidencia", "descripción", "decisión", "justificación"]
PAL_TECNICA = r"bloque|smart app|dll|\.pyd|versi[oó]n de|dependencia|entorno|sklearn|scikit|tensorflow|rasa\.exe|windows|encoding|heredoc|script|error de|fix|ejecutable"
PAL_METODOL = r"fuga|test|evaluaci|umbral|lote|compuerta|congel|etiqueta|revisi|kappa|g[1-7]\b|muestra|dise[ñn]o|frase|protocolo|corpus|partici|desviaci"
PAL_VALIDEZ = r"fuga|evaluaci[oó]n|test|frases? (real|del lote)|umbral|congel|duplicad|g3|kappa|contamin|sesgo|sin revisar|no comparable|artefacto"
txt = (inc["incidencia"] + " " + inc["descripción"]).str.lower()
tec, met = txt.str.contains(PAL_TECNICA, regex=True), txt.str.contains(PAL_METODOL, regex=True)
inc["tipo (heurística)"] = np.where(tec & met, "mixta", np.where(tec, "técnica", np.where(met, "metodológica", "sin clasificar")))
inc["afecta validez (heurística)"] = np.where(txt.str.contains(PAL_VALIDEZ, regex=True), "posible: revisar", "no declarado")
mostrar = inc.assign(descripción=inc["descripción"].str.slice(0, 170), decisión=inc["decisión"].str.slice(0, 120))[["fecha", "tipo (heurística)", "afecta validez (heurística)", "incidencia", "descripción", "decisión"]]
rotulo("Bitácora del proyecto (registro de decisiones, no datos del estudio)", f"{len(inc)} incidencias")
print("Incidencias:", len(inc), "| por tipo (heurística):", inc["tipo (heurística)"].value_counts().to_dict(), "| con posible efecto en la validez:", int((inc["afecta validez (heurística)"] != "no declarado").sum()))
display(mostrar)
rotulo("Últimas 5 incidencias, con su justificación completa")
for _, r in inc.tail(5).iterrows():
    print(f"- {r['fecha']} · {r['incidencia']}\n    Decisión: {r['decisión'][:400]}\n    Justificación: {r['justificación'][:400]}")

▌ORIGEN: Bitácora del proyecto (registro de decisiones, no datos del estudio) — 72 incidencias
Incidencias: 72 | por tipo (heurística): {'metodológica': 47, 'mixta': 12, 'sin clasificar': 7, 'técnica': 6} | con posible efecto en la validez: 33

         fecha tipo (heurística) afecta validez (heurística)                                                             incidencia                                                            descripción                                                               decisión
0   2026-10-01    sin clasificar                no declarado                                             N/A (planificación piloto)  La MPSR no otorga permiso para desplegar el chatbot en su platafor...  Rediseñar P01/P11.2/P12/P13: despliegue en canal propio (WhatsApp/...
1   2026-10-01      metodológica            posible: revisar                                              N/A (diseño metodológico)  No es logísticamente viable recontactar a los mismos sujetos de P0...  Se cambia el diseño de pre-test/post-test de un solo grupo a dos g...
2   2026-10-02      metodológica                no declarado                                             N/A (resolución de diseño)  Se contrastó el archivo Encuestas_simuladas_TramiFacil_MPSR_120_v2...  Se revierte a n=120 (fórmula de poblaciones finitas + análisis de ...
3   2026-10-02    sin clasificar                no declarado                                                      N/A (instrumento)  Se identificó que TramiFácil es una herramienta de uso interno del...  Se corrigió la Ficha de Diagnóstico P01 (se eliminó la opción de c...
4   2026-09-29           técnica                no declarado                                                     N/A (entorno, P15)  requirements.txt pedía scikit-learn>=1.3 y rasa sin versión; Rasa ...  Se fijaron versiones verificadas: rasa==3.6.21, scikit-learn==1.1....
5   2026-09-29           técnica                no declarado                                                     N/A (entorno, P15)  Windows Smart App Control bloquea el ejecutable no firmado venv/Sc...  Todos los comandos de Rasa se ejecutan como 'python -m rasa ...'; ...
6   2026-09-29      metodológica                no declarado                                          P08 (configs/rasa_config.yml)  batch_size: [64, 128] en Rasa no prueba dos valores: hace crecer e...  batch_size pasa a ser un valor único por corrida; scripts/run_rasa...
7   2026-10-02             mixta                no declarado                                                 N/A (experiments/*.py)  Los scripts de experiments/ tenían rutas absolutas de otro sistema...  Se reemplazaron solo las rutas por rutas relativas a la raíz del r...
8   2026-10-02      metodológica                no declarado                                                   P05 (corpus starter)  La partición del corpus starter es 162/81/81 (50/25/25), no 70/15/...  Se mantiene la partición recibida para las corridas preliminares (...
9   2026-10-02      metodológica                no declarado                                               P02/P03 (corpus starter)  El corpus starter tiene 54 intenciones; el protocolo (sección 2.3,...  Pendiente: actualizar el protocolo a 54 intenciones o fusionar/eli...
10  2026-10-02      metodológica            posible: revisar                                               P03/P05 (corpus starter)  Las 54 intenciones tienen solo 2 grupos base_phrase_id (3 utteranc...  Ampliar el corpus a >= 3 grupos por intención (idealmente con fras...
11  2026-10-02           técnica                no declarado                     P06 (BASE-SVM-C1-s42 vs EXP_BASELINE_SVM_S42_2026)  scripts/train_baseline.py normaliza el texto (minúsculas, sin tild...  Se conservan ambos resultados; ambos seleccionan C=1 y el F1 macro...
12  2026-10-02           técnica                no declarado                                             RASA-e150-b64-d50 (Fase 2)  La ejecución de scripts/run_rasa_grid.py se interrumpió dos veces:...  Se agregó la opción --only-repetitions, que reutiliza la Fase 1 ya...
13  2026-10-02      metodológica                no declarado                 BASE-SVM-C1-s10..s50 / BASE-LOGREG-C1.0-s10..s50 (P10)  Las 5 repeticiones del baseline dan resultados idénticos (DE = 0):...  Pendiente decidir con la asesora: variar la partición por repetici...
14  2026-10-02      metodológica            posible: revisar                              BASE-* y RASA-e150-b64-d50-s10..s50 (P11)  Ningún método alcanza el criterio F1 macro >= 0.85 en test: TF-IDF...  No se fija todavía la arquitectura final de OE2; se registra que R...
15  2026-10-02      metodológica                no declarado                                              EXP_BASELINE_SVM_S42_2026  F1-macro inicial (0.2975) muy por debajo de la meta (>=0.85) con c...  Se amplio el corpus de 2 a 4 grupos de parafrasis por intencion (3...
16  2026-10-02             mixta                no declarado                                     N/A (experiments/expand_corpus.py)  expand_corpus.py cargaba los grupos 1 y 2 desde /home/claude/corpu...  Se reconstruye la misma estructura CORPUS desde el corpus v1 conse...
17  2026-10-02             mixta                no declarado                             EXP_BASELINE_SVM_S42_2026 (corpus v2, 648)  train_baseline_p07.py tenía escrito a mano 'corpus_metadata.csv (3...  La etiqueta del corpus ahora se calcula desde los datos (n.º de ut...
18  2026-10-02      metodológica            posible: revisar                                                   P04 (corpus v2, 648)  La auditoría detecta fuga por paráfrasis: U0018 'Quisiera saber el...  Pendiente: ejecutar scripts/audit_corpus.py --apply para fusionar ...
19  2026-10-02      metodológica            posible: revisar                                               P02/P04 (corpus v2, 648)  Los grupos 3 y 4 de las 44 intenciones no conversacionales se gene...  Pendiente: reemplazar o complementar estas plantillas con consulta...
20  2026-10-02      metodológica            posible: revisar                                                   P05 (corpus v2, 648)  La nueva partición es 486/81/81 (75/12.5/12.5), no 70/15/15; cada ...  Se mantiene la partición recibida para esta corrida preliminar; pe...
21  2026-10-02             mixta            posible: revisar                                          P06 (BASE-SVM-C0.1 corpus v2)  Con la normalización de texto de scripts/ el SVM obtiene F1 macro ...  Se conservan ambos resultados; ambos seleccionan C = 0.1 en valida...
22  2026-10-02      metodológica            posible: revisar                  BASE-* y RASA-e200-b128-d20-s10..s50 (P11, corpus v2)  Con el corpus v2 (648) ningún método alcanza F1 macro >= 0.85 en t...  No se fija todavía la arquitectura final de OE2; Rasa/DIET vuelve ...
23  2026-10-02      metodológica                no declarado                                                     RASA-* (corpus v2)  La grilla completa tarda 1 h 26 min en CPU (12 combinaciones + 5 r...  Ejecución completa en una sola pasada, exit=0; la salida queda en ...
24  2026-10-02           técnica                no declarado                                  N/A (estructura del repositorio, P15)  Había dos carpetas de código (experiments/ y scripts/); train_base...  Se consolidó todo en scripts/: expand_corpus.py, train_baseline_p0...
25  2026-10-02    sin clasificar                no declarado                                                       P09 (domain.yml)  Las 44 respuestas de trámites usan información típica de TUPA muni...  Se completaron las 54 respuestas (P09; domain_v2.yml reemplaza a d...
26  2026-10-02      metodológica            posible: revisar                                     P11.1 (smoke test, 54 intenciones)  Con consultas nuevas (1 por intención) el modelo acierta 46/54 int...  Se registra el resultado sin modificar el corpus ni el modelo; pen...
27  2026-10-02      metodológica            posible: revisar                               P11.1 (rasa test nlu --cross-validation)  La validación cruzada sobre data/nlu_full.yml arma folds al azar s...  No se reporta este F1 como métrica de P11 ni para el criterio F1 >...
28  2026-10-02      metodológica            posible: revisar                            P11.1 (re-entrenamiento del modelo de humo)  Los comandos propuestos tenían tres problemas: '--data data/' incl...  Se entrenó con '--data data/nlu.yml data/rules.yml' (solo train), ...
29  2026-10-02             mixta            posible: revisar                                          P11.1 (smoke test vía script)  rasa shell es interactivo y no puede ejecutarse de forma automátic...  Se reemplazó por scripts/smoke_test.py, que envía al modelo comple...
30  2026-10-02      metodológica            posible: revisar                                       P11.1 (ampliación del corpus v3)  El smoke test de P11.1 mostró 8 intenciones mal clasificadas (afir...  Se agregaron 60 frases coloquiales en 20 grupos nuevos (corpus/amp...
31  2026-10-02      metodológica            posible: revisar                                          P11.1 (smoke tests contra v3)  Las 54 consultas del primer smoke test quedaron contaminadas para ...  Se redactaron 54 consultas nuevas (tests/smoke_test_queries_v2.csv...
32  2026-10-02      metodológica            posible: revisar                                            P11.1 (criterios de salida)  No se cumplen los criterios de salida de P11.1: F1 macro en el tes...  No se autoriza el paso a P11.2 (pre-piloto con personas). Se regis...
33  2026-10-02      metodológica            posible: revisar                         RASA-e150-b64-d20 (grilla P08 sobre corpus v3)  Al repetir la grilla con el corpus v3 la mejor combinación en vali...  Se conservan ambos resultados; los logs del corpus v2 se archivaro...
34  2026-10-02      metodológica            posible: revisar                           P11.1 (efectos secundarios de la ampliación)  En el test real la ampliación mejoró reporte_alumbrado_publico (0....  No se corrige más el corpus mirando estos resultados del test; se ...
..         ...               ...                         ...                                                                    ...                                                                    ...                                                                    ...
37  2026-10-03      metodológica            posible: revisar                P11.2a (preparación del lote real y de la partición v3)  P11.1 no cumplió el criterio de salida y la partición V1.1 (P05) d...  Se ejecutó la Parte A: scripts/ingest_real_lote.py, split_corpus_v...
38  2026-10-03             mixta                no declarado                                      P11.2a (catálogo real del lote 1)  El catálogo situaciones_lote1_v1.csv no estaba entre los archivos ...  Se reemplazó la plantilla por el catálogo del tesista (copia idént...
39  2026-10-03      metodológica            posible: revisar                          P11.2a (seguimiento del lote 1, plantilla v3)  El seguimiento de las versiones anteriores (v1/v2) contaba persona...  Se adopta la plantilla v3 (hojas Blancos y Cobertura, medida por i...
40  2026-10-03             mixta            posible: revisar  Documentos V1.2 (corrección de las 5 discrepancias de verificar_re...  scripts/verificar_referencias.py encontró 5 discrepancias entre el...  En el repositorio, donde el repositorio es la fuente: README (la p...
41  2026-10-03      metodológica                no declarado                                                        Piloto (diseño)  El piloto planificado (120 personas, dos visitas, WhatsApp) no cab...  Piloto exploratorio de 60 personas en una sola sesión asistida (V1...
42  2026-10-04    sin clasificar                no declarado                                                Piloto (siguiente paso)  Faltaban el formulario de sesión y el registro de sesiones; analiz...  Se incorporaron a docs/piloto/ el formulario de sesión asistida (W...
43  2026-10-04    sin clasificar                no declarado                                           Piloto (ajustes al registro)  En la hoja Resumen del registro, los textos de meta usaban la func...  Se reemplazaron por la v2 el registro de sesiones y el formulario ...
44  2026-10-04    sin clasificar                no declarado                                              Piloto (demo simulada v4)  La demo sintética del registro mostraba «04» y «001» en los textos...  Se reemplazó la demo de docs/piloto/ejemplos_simulados/ por Regist...
45  2026-10-04      metodológica                no declarado                                            Datos simulados (detección)  El libro Lote1_Transcripcion_v1__1_.xlsx solo estaba marcado como ...  Se reforzó la detección con un módulo común, scripts/deteccion_sim...
46  2026-10-05      metodológica                no declarado                                    Lote 1 (plantilla de transcripción)  El tesista transcribirá el lote 1 en Lote1_Transcripcion_v1.xlsx y...  Se incorporó la plantilla vacía a docs/lote_real_1/ (el libro llen...
47  2026-10-05      metodológica                no declarado                                                  Compuertas por avance  La regla del piloto de la incidencia «Piloto (diseño)» condicionab...  El protocolo V1.4 (documentos _v7) reemplaza la fecha de corte por...
48  2026-10-05      metodológica                no declarado                          Compuertas por avance (reemisión de archivos)  El formulario de sesión asistida v2 conservaba una casilla que cit...  Se reemplazaron por la v3 el formulario de sesión asistida (Word y...
49  2026-10-05           técnica                no declarado                                         Demostración simulada completa  El tesista quiere demostrar el pipeline del curso con datos simula...  Se ejecutó la demostración completa con scripts/demostracion_simul...
50  2026-10-05      metodológica            posible: revisar                  Umbral aplicado a las predicciones guardadas del test  Tras la demostración simulada se pidió verificar que, en el flujo ...  Verificado: fallback_threshold.py --fase test ya leía solo predict...
51  2026-10-07      metodológica                no declarado                                         Protocolo V1.5 (documentos v8)  El protocolo y la nota se reemitieron para incorporar la demostrac...  Se instalaron en docs/ los PDF v8 de protocolo (V1.5, 6 oct.) y no...
52  2026-10-07      metodológica                no declarado                                          Lote 1 REAL (paso A: ingesta)  El tesista aplicó el lote 1 con 25 personas reales y lo transcribi...  Se usó Lote1_TranscripcionV1.2.xlsx (169 frases leídas de la hoja ...
53  2026-10-07      metodológica                no declarado                                Lote 1: revisión de etiquetas y lote 1b  Lote 1: revisión de etiquetas (11 cambios, 0 descartes); 4 intenci...  Se trasladaron las 169 decisiones de la revisión humana (158 OK, 1...
54  2026-10-07      metodológica                no declarado                                     Lote 1 REAL (libro combinado V1.3)  Había que reunir en un solo libro los 25 participantes del lote 1 ...  Se combinaron en un libro nuevo (privado, fuera de Git) las celdas...
55  2026-10-07      metodológica                no declarado                          Lote 1 REAL (ingesta con P26–P28 transcritos)  El tesista marcó P26–P28 como Transcrito en el libro lleno_v2 y pi...  Se combinó de nuevo (libro privado versión v4; base y fuente intac...
56  2026-10-07      metodológica                no declarado                Lote 1 REAL (revisión del lote 1b y --aplicar-revision)  Faltaba revisar las 12 frases nuevas (P26–P28) para completar la c...  Se trasladaron las 12 decisiones del tesista (12 OK; emparejadas p...
57  2026-10-07      metodológica                no declarado                                      Compuertas G1 y G2 (datos reales)  El tesista revisó el reporte de datos personales del lote 1 y 1b y...  Se instaló revision_pii.txt tal como lo entregó el tesista (idénti...
58  2026-10-07      metodológica            posible: revisar                                  TUPA v10 (dry-run de aplicar_tupa.py)  El tesista entregó Verificacion_TUPA_v10 y pidió un dry-run para v...  scripts/aplicar_tupa.py no existía: se escribió. Dry-run con la v1...
59  2026-10-07      metodológica            posible: revisar                              Lote 1 REAL (etapa C: partición detenida)  split_corpus_v3.py se negó a escribir la partición: 1 frase (norma...  No se escribió ninguna salida y no se cambió el criterio de partic...
60  2026-10-07      metodológica                no declarado                       Lote 1c (preparación) y dry-run de domain_v3.yml  Con los descartes de R0147 y R0136, agradecimiento y despedida que...  Dry-run sobre domain_v3.yml: entran las mismas 26 filas (0 problem...
61  2026-10-07      metodológica                no declarado                                     Lote 1c REAL (ingesta) y descartes  El tesista aplicó el lote 1c a 4 personas (P29–P32, formulario G, ...  Se amplió el catálogo y la ingesta hasta P32 y se ingestó desde un...
62  2026-10-08      metodológica            posible: revisar  Partición v3 real, selección, umbral, test único, TUPA aplicado, s...  G3 NO cumplida: en el test real (114 frases, una sola evaluación) ...  Se mantiene G3 como NO cumplida y el criterio 0,75; el test no se ...
63  2026-10-09             mixta            posible: revisar   Refinamiento previo al lote 2 y congelamiento del modelo y el umbral  Con aprobación del tesista se usó 1 de 2 ciclos de refinamiento, s...  Se mantiene G3 como No cumplida, lote 1; el lote 2 se evalúa una s...
64  2026-10-08      metodológica            posible: revisar                   Lote 2 (congelamiento previo del modelo y el umbral)               Se rehízo el congelamiento previo al lote 2 con --forzar  Congelamiento anterior (2026-10-09T01:20:34+00:00, modelo be1a5ad0...
65  2026-10-09             mixta            posible: revisar  Constancia domiciliaria aplicada, congelamiento rehecho y SVM base...  Con aprobación del tesista se aplicó el dry-run 3 (texto de consta...  eval_lote2.py evaluará DIET y SVM UNA sola vez en la misma pasada ...
66  2026-10-09      metodológica            posible: revisar        Frase del lote 2 mostrada por error en una salida de la consola  Al inspeccionar la estructura del libro Lote2_Transcripcion_v1.xls...  Se registra este incidente y se refuerza la práctica: los scripts ...
67  2026-10-09             mixta            posible: revisar  Evaluación única del lote 2 (G3): F1 macro 0,9072 y limitación del...  Con modelo y umbral congelados y 16 verificaciones previas OK, se ...  No se repite la evaluación ni se cambia el umbral ni el modelo; la...
68  2026-10-09      metodológica            posible: revisar  Congelamiento del modelo medido en el lote 2 (G5 real) y protocolo...  Se congeló sin reentrenar el modelo medido en el lote 2 (LOTE2-FIN...  G5 se evaluó solo con hashes coincidentes y fecha posterior a G3 y...
69  2026-10-09    sin clasificar                no declarado  Registro real del pre-piloto rehecho a partir de uno mezclado con ...  El registro del pre-piloto se había creado con filas generadas por...  Se conserva el descartado solo como evidencia y no cuenta para G6....
70  2026-10-09      metodológica            posible: revisar  Una prueba de humo reescribió archivos derivados reales del lote 2...  Al ejecutar toda la batería tests/smoke_*.py para el material de C...  Se quitó esa comprobación de tests/smoke_lote2.py (una prueba nunc...
71  2026-10-09             mixta            posible: revisar  La demo en vivo agregó assistant_id a configs/rasa_config_lote2.ym...  Al probar scripts/demo_vivo.ps1 de principio a fin, 'rasa train nl...  demo_vivo.ps1 entrena ahora con una copia de la configuración (mod...

▌ORIGEN: Últimas 5 incidencias, con su justificación completa
- 2026-10-09 · Evaluación única del lote 2 (G3): F1 macro 0,9072 y limitación del script de evaluación
    Decisión: No se repite la evaluación ni se cambia el umbral ni el modelo; las limitaciones quedan declaradas en logs/avance/eval_lote2_notas.md y se reportan junto con el resultado; los casos mal clasificados se revisan solo por id y con aprobación del tesista
    Justificación: El resultado es más alto que el estimado por validación cruzada del lote 1 (0,787–0,799); las 56 situaciones son las mismas del lote 1 (independiente por personas, no por situaciones), el entrenamiento incluye frases reales del lote 1 y 13 frases idénticas al entrenamiento se excluyeron del test; leer con cautela y como medición en este diseño, no como generalización a situaciones nuevas
- 2026-10-09 · Congelamiento del modelo medido en el lote 2 (G5 real) y protocolo V1.7 / Nota v10
    Decisión: G5 se evaluó solo con hashes coincidentes y fecha posterior a G3 y G4; el modelo congelado no vuelve a cambiar sin --forzar --motivo; las pruebas con datos falsos ya no suponen que el congelamiento real no exista
    Justificación: La Nota v10 dice «4 de 7 compuertas con datos reales (G1, G2, G3 y G4)» y el tablero ya muestra 5 de 7 (G5): diferencia declarada entre el documento (anterior al congelamiento) y el repositorio; el documento no se modifica desde aquí
- 2026-10-09 · Registro real del pre-piloto rehecho a partir de uno mezclado con filas de un asistente
    Decisión: Se conserva el descartado solo como evidencia y no cuenta para G6. El tablero (G6) lee ahora únicamente Registro_Sesiones_Prepiloto.xlsx por nombre exacto, para que ni el v2 ni el descartado puedan tomarse por error. analizar_piloto.leer_registro acepta además códigos PP (antes solo SA). No se ejecutó analizar_piloto.py y no se tocó corpus/real/.
    Justificación: Un registro con filas generadas por un asistente no puede entrar al análisis. Las filas se descartaron antes de leerlas y sin usarlas en ninguna cifra; las cifras de G6 salen solo del libro real con PP01–PP07. No cambia ningún criterio de las compuertas.
- 2026-10-09 · Una prueba de humo reescribió archivos derivados reales del lote 2 (contenido sin cambios)
    Decisión: Se quitó esa comprobación de tests/smoke_lote2.py (una prueba nunca debe ejecutar un script del lote 2 con las rutas reales); smoke_lote2 queda en 51/51 y no vuelve a escribir en corpus/v3_lote2/. Se declara aquí; no se restaura la fecha original porque no se guardó una copia.
    Justificación: El archivo se reescribió con los mismos datos y las mismas entradas (sha256 del entrenamiento y de los congelamientos coinciden con los del resumen), de modo que ninguna cifra reportada cambia. El riesgo era sobrescribir datos reales con una prueba de humo; se elimina la causa.
- 2026-10-09 · La demo en vivo agregó assistant_id a configs/rasa_config_lote2.yml (config del modelo congelado) y la huella cambió
    Decisión: demo_vivo.ps1 entrena ahora con una copia de la configuración (models/demo_vivo/config_oficial_copia.yml, ignorada por Git), nunca con el archivo congelado. Se vuelve a correr la demo completa para confirmar que no cambia ninguna huella.
    Justificación: La configuración forma parte del congelamiento (G5). Un cambio no declarado de su huella invalidaría el congelamiento; se detectó el mismo día, se restauró el contenido exacto y se declara aquí.

### Cómo leer el resultado (cuaderno 12)
- Cada fila es una desviación o un error **declarado**: por ejemplo, que se mostró por descuido una frase del lote 2 en una salida (y no se usó para ajustar nada), que la evaluación del lote 2 tiene un artefacto en la sección «umbral», o que el registro del pre-piloto se rehízo porque se había mezclado con filas generadas por un asistente.
- «posible: revisar» no quiere decir que la validez esté comprometida; marca las incidencias que tocan evaluación, umbral, congelamiento o fuga, para que el docente las lea con más cuidado.

### 5. Matriz de trazabilidad P01–P16 / G1–G7
La celda siguiente necesita el tablero de compuertas.

In [7]:
tb = leer_json("logs/avance/estado_compuertas.json")

### Matriz de trazabilidad
**Qué se hace:** una tabla única que enlaza cada **paso (P01–P16)** y cada **compuerta (G1–G7)** con el script que lo ejecuta, el archivo de evidencia, el resultado y su estado (*ejecutado / simulado / planificado / pendiente*).
**Por qué:** permite al docente seguir un hilo desde el protocolo hasta el dato. El estado de las compuertas se toma **del tablero**, no se escribe a mano.

In [8]:
tp = pd.DataFrame(meta["traza_pasos"], columns=["id", "paso", "script(s)", "archivo de evidencia", "resultado", "estado"])
tc = []
for gid, nombre, scr, evid in meta["traza_compuertas"]:
    c = next(x for x in tb["compuertas"] if x["id"] == gid)
    estado = {"Cumplida": "ejecutado", "No cumplida": "ejecutado (no cumplida)"}.get(c["estado"], "pendiente")
    if gid == "G7":
        estado = "pendiente (solo demostración simulada)"
    tc.append([gid, f"Compuerta: {nombre}", scr, evid, c["nota"][:230], estado])
tc = pd.DataFrame(tc, columns=tp.columns)


def en_paquete(ev):
    ruta = ev.split(",")[0].split(" + ")[0].strip()
    ruta = ruta.replace("…", "").replace("*", "")
    return "sí" if (BASE / ruta).exists() else "no (privado o ignorado por Git)"


matriz = pd.concat([tp, tc], ignore_index=True)
matriz["en este paquete"] = matriz["archivo de evidencia"].map(en_paquete)
rotulo("Trazabilidad del proyecto (el rótulo de origen de cada dato está en cada cuaderno por paso)")
print("Estados:", matriz["estado"].value_counts().to_dict())
display(matriz)

▌ORIGEN: Trazabilidad del proyecto (el rótulo de origen de cada dato está en cada cuaderno por paso)
Estados: {'ejecutado': 19, 'simulado': 2, 'pendiente': 2, 'ejecutado (no cumplida)': 1, 'pendiente (solo demostración simulada)': 1}

        id                                         paso                                                              script(s)                                                   archivo de evidencia                                                              resultado                                  estado                  en este paquete
0      P01          Diagnóstico y línea base de tiempos                                                    simular_P14_n120.py                 corpus/Encuestas_simuladas_TramiFacil_MPSR_120_v2.xlsx     Línea base SIMULADA (n = 120) del diseño V1.2; no es dato de campo                                simulado                               sí
1      P02                      Construcción del corpus                               expand_corpus.py, apply_ampliacion_v3.py                                             corpus/corpus_metadata.csv                    708 frases sintéticas, 54 intenciones, 9 categorías                               ejecutado                               sí
2      P03                         Auditoría del corpus                                                        audit_corpus.py                         logs/audit_report.txt, corpus/corpus_audit.csv                                      Duplicados y desbalance auditados                               ejecutado                               sí
3      P04               Control de fuga por paráfrasis                                                        audit_corpus.py                                             corpus/corpus_summary.json                                  leaks_detected = 0 en la partición v3                               ejecutado                               sí
4      P05              Partición train/validation/test                    split_corpus.py, split_corpus_v3.py, split_lote2.py              corpus/dataset_split.csv; corpus/v3_real; corpus/v3_lote2    546/81/81 sintético; lote 1 real 707/71/114; lote 2 solo test (267)                               ejecutado  no (privado o ignorado por Git)
5      P06         Normalización (jerga) y formato Rasa                                          common.py, export_rasa_nlu.py                                    configs/jerga_local.csv; data/*.yml                                        Corpus exportado a formato Rasa                               ejecutado  no (privado o ignorado por Git)
6      P07                      Línea base TF-IDF + SVM                               train_baseline_p07.py, train_baseline.py                   logs/baseline_validation.csv, logs/baseline_test.csv                                       SVM C = 10 elegido en validación                               ejecutado                               sí
7      P08                     Rasa NLU / DIET (grilla)                                         run_rasa_grid.py, eval_real.py                                                    logs/v3_real/RASA-*             Grilla epochs {100,150,200} × batch {64,128} × dim {20,50}                               ejecutado  no (privado o ignorado por Git)
8      P09                       Respuestas del dominio             aplicar_tupa.py, aplicar_respuestas.py, humo_respuestas.py                  domain_v3.yml; docs/tupa/Verificacion_TUPA_v10_4.xlsx                           44 respuestas de trámites, 0 con [Verificar]                               ejecutado  no (privado o ignorado por Git)
9      P10                  Repeticiones con 5 semillas                                    run_rasa_grid.py, train_baseline.py                                 logs/v3_real/RASA-e100-b64-d20-s10…s50                                            Semillas 10, 20, 30, 40, 50                               ejecutado  no (privado o ignorado por Git)
10     P11                        Evaluación en el test                                            eval_real.py, eval_lote2.py                   logs/v3_real/test_registro.json; logs/v3_real/lote2/  Lote 1: F1 0,6867 (No cumplida, lote 1). Lote 2 (evaluación única)...                               ejecutado  no (privado o ignorado por Git)
11   P11.1                    Pruebas técnicas internas                                           smoke_test.py, plot_p11_1.py                                              evidencias/p11_1_pruebas/  46/54 intenciones correctas en el smoke test; CV 0,778 inflada por...                               ejecutado                               sí
12  P11.2b                              Pre-piloto (G6)  asistente_local.py, preparar_registro_prepiloto.py, estado_compuer...         docs/piloto/privado/Registro_Sesiones_Prepiloto.xlsx (privado)                 7 sesiones, 5 elegibles; alfa 0,366 con n = 5 (< 0,70)                               ejecutado  no (privado o ignorado por Git)
13     P12  Piloto exploratorio (60 sesiones asistidas)                                                     analizar_piloto.py                     docs/piloto/privado/Registro_Sesiones_Piloto*.xlsx                    Sin sesiones reales aún; solo demostración simulada                               pendiente  no (privado o ignorado por Git)
14     P13              Recolección y cierre del piloto                               analizar_piloto.py, estado_compuertas.py                                          logs/avance/cierre_piloto.txt                                             No existe cierre declarado                               pendiente  no (privado o ignorado por Git)
15     P14                         Análisis estadístico                       stats_analysis.py, analizar_piloto.py, simular_*                         evidencias/simulado_demostracion/…/05_sesiones                     Solo simulado; el análisis real depende de G6 y G7                                simulado  no (privado o ignorado por Git)
16     P15                     Evidencias reproducibles                           congelar_modelo.py, verificar_referencias.py                                     evidencias/, requirements-lock.txt                                        Entorno fijado y huellas sha256                               ejecutado                               sí
17     P16                      Bitácora de incidencias                                                                      —                                                       incident_log.csv                                   Una fila por incidencia o desviación                               ejecutado                               sí
18      G1                   Compuerta: Lote 1 completo                                                    ingest_real_lote.py                                       logs/v3_real/ingesta_reporte.txt        Transcritos 32/15 (≥ 15); intenciones con menos de 3 frases: 0.                               ejecutado  no (privado o ignorado por Git)
19      G2                 Compuerta: Parte B ejecutada                                                    ingest_real_lote.py        logs/v3_real/ingesta_reporte.txt + logs/avance/revision_pii.txt  Ingesta sin errores bloqueantes y revisión de datos personales mar...                               ejecutado  no (privado o ignorado por Git)
20      G3         Compuerta: Calidad con lenguaje real                                            eval_real.py, eval_lote2.py  logs/v3_real/test_registro.json + logs/v3_real/lote2/test_registro...  No cumplida, lote 1. Ciclos de refinamiento: 1/2. Única evaluación...                               ejecutado                               sí
21      G4            Compuerta: Respuestas verificadas                                 aplicar_tupa.py, aplicar_respuestas.py                                 docs/tupa/Verificacion_TUPA_v10_4.xlsx  Alta pendientes: 0; filas con alerta: 0; Corregir o Coincide sin c...                               ejecutado                               sí
22      G5                  Compuerta: Modelo congelado                                                     congelar_modelo.py                                     logs/v3_real/modelo_congelado.json                     Congelado el 2026-10-08 22:17, después de G3 y G4.                               ejecutado                               sí
23      G6                        Compuerta: Pre-piloto                               asistente_local.py, estado_compuertas.py                   docs/piloto/privado/Registro_Sesiones_Prepiloto.xlsx  Alfa de Cronbach 0.366 < 0.7: se corrige el instrumento y se repit...                 ejecutado (no cumplida)  no (privado o ignorado por Git)
24      G7               Compuerta: Sesiones del piloto                               analizar_piloto.py, estado_compuertas.py  docs/piloto/privado/Registro_Sesiones_Piloto*.xlsx + logs/avance/c...                           60 sesiones elegibles y completas (meta 60).  pendiente (solo demostración simulada)  no (privado o ignorado por Git)

### Cómo leer el resultado de esta sección
- **ejecutado:** el paso se hizo con datos del proyecto. **simulado:** solo se demostró con datos inventados (línea base P01, análisis P14). **pendiente:** depende de datos que aún no existen (piloto de 60 sesiones, G7).
- «en este paquete = no» significa que la evidencia vive en una carpeta ignorada por Git por traer datos de personas; los números agregados de esa evidencia están en los cuadernos 04, 05, 10 y 11.

In [9]:
cierre("P15–P16 Reproducibilidad e incidencias")

P15–P16 Reproducibilidad e incidencias — recalculado frente a reportado: 13 cifras · coinciden: 13 · NO coinciden: 0

   paso                    cifra                                                       recalculado                                                         reportado                           fuente de lo reportado coincide
0   P15          versión de rasa                                                            3.6.21                                                            3.6.21  requirements.txt frente a modelo_congelado.json       Sí
1   P15  versión de scikit-learn                                                             1.1.3                                                             1.1.3  requirements.txt frente a modelo_congelado.json       Sí
2   P15        versión de pandas                                                             2.0.3                                                             2.0.3  requirements.txt frente a modelo_congelado.json       Sí
3   P15         versión de numpy                                                            1.23.5                                                            1.23.5  requirements.txt frente a modelo_congelado.json       Sí
4   P15         versión de scipy                                                            1.10.1                                                            1.10.1  requirements.txt frente a modelo_congelado.json       Sí
5   P15    versión de tensorflow                                                            2.12.0                                                            2.12.0  requirements.txt frente a modelo_congelado.json       Sí
6    G5            sha256 modelo  be1a5ad06357b26370fc14f780f49cbf205b08dbe5fe3af383625e44f64b10d9  be1a5ad06357b26370fc14f780f49cbf205b08dbe5fe3af383625e44f64b10d9               logs/v3_real/modelo_congelado.json       Sí
7    G5            sha256 config  e975783f2bcd6dac366b2ff53677c5221ef77044ec23fb615c3d763dcadbf9e4  e975783f2bcd6dac366b2ff53677c5221ef77044ec23fb615c3d763dcadbf9e4               logs/v3_real/modelo_congelado.json       Sí
8    G5           sha256 dominio  7a69ac91c32cf439e82b4c34a553ec066a71d4041b1b8632288864d36a7756b5  7a69ac91c32cf439e82b4c34a553ec066a71d4041b1b8632288864d36a7756b5               logs/v3_real/modelo_congelado.json       Sí
9    G5            sha256 corpus  c035252d63aa89e11295279b363c98d66b9f2e608008b82390b15ce40a6a4adc  c035252d63aa89e11295279b363c98d66b9f2e608008b82390b15ce40a6a4adc               logs/v3_real/modelo_congelado.json       Sí
10   G5            sha256 umbral  410d9898240ae0ea5118e5d5010af195fa21d0a118c7967875875cd956f8fe4b  410d9898240ae0ea5118e5d5010af195fa21d0a118c7967875875cd956f8fe4b               logs/v3_real/modelo_congelado.json       Sí
11   G5                 umbral t                                                               0.5                                                               0.5                                   Protocolo V1.8       Sí
12   G5  frases de entrenamiento                                                               943                                                               943                  Protocolo V1.8 (707 + 185 + 51)       Sí

DISCREPANCIAS (recalculado ≠ reportado): ninguna
Rasa disponible: False · paquete privado: True

## (d) Cómo leer el resultado
- El entorno del congelamiento es Python 3.10.11 con Rasa 3.6.21, TensorFlow 2.12.0, scikit-learn 1.1.3, pandas 2.0.3, numpy 1.23.5 y scipy 1.10.1; `requirements.txt` coincide con esas versiones.
- **«intacto»** en los cinco componentes = el modelo, el dominio (54 respuestas), la configuración, el entrenamiento (943 frases) y el umbral son exactamente los congelados; el congelamiento es **anterior** a abrir el lote 2 y no se reentrenó después de medir.
- La **bitácora** declara cada desviación (por ejemplo, una frase del lote 2 mostrada por error en una salida, el artefacto de la sección «umbral», el registro del pre-piloto rehecho y una prueba de humo que reescribió archivos derivados con el mismo contenido). La columna «afecta validez» es una **heurística** por palabras clave, no una clasificación del tesista.
- La **matriz** une cada paso y compuerta con su script, su evidencia y su estado.

## Limitaciones
- Sin el paquete privado no se pueden verificar el modelo ni el entrenamiento (se muestran las huellas guardadas).
- El commit declarado en el congelamiento termina en «-modificado» (había cambios sin confirmar al congelar); lo que garantiza la integridad son las huellas sha256, no el commit.